kafka:
  bootstrap.servers: "rpk0.bitquery.io:9092,rpk1.bitquery.io:9092,rpk2.bitquery.io:9092"
  security.protocol: "SASL_PLAINTEXT"
  sasl.mechanism: "SCRAM-SHA-512"
  sasl.username: "<your_username_here>"
  sasl.password: "<your_password_here>"
  group.id: "username-group-transfers"
  ssl.endpoint.identification.algorithm: "none"
  enable.auto.commit: false  
consumer:
  topic: solana.transfers.proto
  partitioned: true
  auto.offset.reset: "earliest"
processor:
  buffer: 100
  workers: 8
log_level: "debug" 